Traceback (most recent call last):
  File "main.py", line 110, in <module>
  File "main.py", line 42, in request_server
  File "requests\api.pyc", line 107, in post
  File "requests\api.pyc", line 53, in request
  File "requests\sessions.pyc", line 468, in request
  File "requests\sessions.pyc", line 576, in send
  File "requests\adapters.pyc", line 437, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='77.131.38.212', port=8080): Max retries exceeded with url: /index/register/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x02C5D090>: Failed to establish a new connection: [Errno 10060] Une tentative de connexion a \xe9chou\xe9 car le parti connect\xe9 n\x92a pas r\xe9pondu convenablement au-del\xe0 d\x92une certaine dur\xe9e ou une connexion \xe9tablie a \xe9chou\xe9 car l\x92h\xf4te de connexion n\x92a pas r\xe9pondu',))
